### ISSUE TITLE
[question] unused metadata PatchSet?

### ISSUE THREAD

**Issue by sanzoghenzo** [vfarcic/crossplane-kubernetes#4]
Hi @vfarcic, thanks for your great work in spreading k8s and gitops knowledge!

I was wondering why there's a PatchSet named `metadata` in all your compositions, but it is never used/called in the actual patch (even more so now that you switched to functions).

From what I can read in the documentation, PatchSets would only be applied to resources that include them using `type: PatchSet` and `name: metadata` in the patches, but there's no such thing anywhere in your compositions.

Am I reading the documentation wrong, or the metadata PatchSet is unused/useless?

**Comment by vfarcic** [comment]
You're absolutely right. It should not be there. It's a leftover from the early versions of that Configuration. I just removed it.
